### ISSUE TITLE
The build.py

### ISSUE THREAD

**Issue by Lvc4** [Hoog3059/CasioScripts#1]
does not output anythint than a text file. But the fxcg50 needs a .g3a file

**Comment by Hoog3059** [comment]
That's correct. It's not really "building" the Casio scripts. Rather it removes the custom formatting I've used for the scripts so it's readable by the calculator.

The Casio FX CG 50 can run assembly code in the form of .g3a binary files, scripts in Python and scripts in Casio Basic. The programs in this repository were written in Casio Basic and were never meant to be compiled to the .g3a format.

**Comment by Lvc4** [comment]
But how can i run the script?

**Comment by Hoog3059** [comment]
In the repository you find the correctly formatted scripts in the “format” folder. You have to copy these files to the calculator by USB. You can find further information on how to do this in the manual: https://info.casio.co.uk/hubfs/CAL/Resources/fx-CG50%20Software%20v3.3%20Manual.pdf

You can find it on page 8-9 (aka page 305) under the subtitle “To convert a text file to a program”.
